### ISSUE TITLE
I can't override style settings from the document's YAML block

### ISSUE THREAD

**Issue by oliver-dew** [msprev/panzer#17]
Hello, I'm trying to override some of my style settings from the markdown document's YAML data block, but it's not working. Here is my style.yaml (this all works as it should):

```
Letter:
    parent:
        - Base
  #  all:
      #  metadata:

    latex:
        template: myletter.tex
        metadata:
            fontsize: 12pt
            geometry: margin=1in
            mainfont: Minion Pro
            # opening: false
            fromaddress: |
                    | my street
                    | my town
                    | my postcode
                    | my email
            toaddress:  |
                    | Department
                    | University
                    | City
            closing: Yours sincerely
            signature: my name
```

I am trying to override latex: metadata: toaddress

I have tried various things in the document's YAML block eg:

```

---
style: Letter

metadata:
    - toaddress: person I'm writing to
...
```

and also:

```

---
style: Letter

latex:
    metadata:
        - toaddress: person I'm writing to
...
```

Both of them with and without the hyphens.
But every time it just gets processed with the settings from the styles.yaml file. What am I doing wrong?

Thanks.

**Comment by oliver-dew** [comment]
As an experiment, I tried defining a style in the YAML block which inherits from the letter style:

```
---
style: Letter2
styledef:
    Letter2:
        parent:
            - Letter
        latex:
            metadata:
                toaddress: |
                        | addressee name

```

This works. But according to the documentation I can just override the setting I want can't I?

> Style settings can be overridden by adding the appropriate field outside a style definition in the document’s metadata block
