### ISSUE TITLE
Support 'includes' directory similar to 'template' directory

### ISSUE THREAD

**Issue by bpj** [msprev/panzer#29]
I have a directory `~/.pandoc/includes/` and often a directory `./includes/` containing reusable header includes files like `fancy-headings.ltx`. The irritating thing about this is that when using panzer I still have to supply these as command line options with a full path and without smartness in the lookup:

``` yaml
commandline:
  include-in-header:
    - '`/home/bpj/.pandoc/includes/fancy-headings.ltx`'
```

In short I wish I could say

``` yaml
headerincludes:
  # These load titlesec and does stuff with it
  - kill: plain-headings.ltx 
  - use:  fancy-headings.ltx
beforebodyincludes:
  - use:  foo.ltx
afterbodyincludes:
  - kill: bar.ltx
```

and have panzer look for the files similarly to how it looks for filters and templates,

| \#  | look for                                               |
|:----|:-------------------------------------------------------|
| 1   | `./fancy-headings.ltx`                                 |
| 2   | `./includes/fancy-headings.ltx`                        |
| 3   | `./includes/fancy-headings/fancy-headings.ltx`         |
| 4   | `~/.panzer/includes/fancy-headings.ltx`                |
| 5   | `~/.panzer/includes/fancy-headings/fancy-headings.ltx` |

building an includes list for each of the three locations.

**Notes:**

-   I only ever use header includes this way, but it seems to make sense to support before/after body includes as well. If they are not included somebody will certainly find a need for them! :-)

-   I'm not enough of a Python programmer, my language of choice being Perl, to suggest any code for doing this, but hopefully the code for looking up filters, templates etc. can largely be reused.
