### ISSUE TITLE
Suggestion: allow compact style field

### ISSUE THREAD

**Issue by dnebauer** [msprev/panzer#35]
One of the excellent effects of using panzer has been that it massively streamlines my document metadata block by moving its contents to the style file. It is not uncommon for metadata block to now look something like:

```yaml
title:  "My Doc"
author: Me
date:   Now
style:
  - Standard
  - Latex12pt
  - PaginateSections
```

Over half the lines are due to the `style` field. If style values were parsed as comma- and/or space-delimited lists in themselves, this could be written as:

```yaml
title:  "My Doc"
author: Me
date:   Now
style:  Standard, Latex12pt, PaginateSections
```

This is intuitive, more compact (displaying more document content when I open a file) and perhaps even elegant 

Assuming style names have never been able to contain spaces or commas, such a change would be universally backwards-compatible. Is there any technical reason this could not be implemented?
