### ISSUE TITLE
WARNING: no global style definitions found

### ISSUE THREAD

**Issue by lyndondrake** [msprev/panzer#42]
Hi,

I must be making a basic mistake, but I can't get `panzer` to recognise my style definitions. I get this warning when I run panzer:

`WARNING: no global style definitions found
`

but I have styles in:

```
$ ls ~/.panzer/styles/
styles.yaml
```

Any thoughts?

**Comment by msprev** [comment]
I'm not sure... What does your `style.yaml` file contain? If it is empty then panzer won't be able to find any definitions there.

**Comment by lyndondrake** [comment]
```
Base:
  latex:
    metadata:
      papersize: a4
      mainfont: Skolar PE
      mainfontoptions: Numbers=OldStyle

Article:
  parent:
    - Base
  all:
    metadata:
      numbersections: true
  latex:
    metadata:
      documentclass: article
      papersize: a4
      mainfont: Skolar PE
      mainfontoptions: Numbers=OldStyle
      numbersections: true
      fontsize: 12pt
  pdf:
    metadata:
      documentclass: article
      papersize: a4
      mainfont: Skolar PE
      mainfontoptions: Numbers=OldStyle
      numbersections: true
      fontsize: 12pt
      standalone: true
    commandline:
      pdf-engine: `xelatex`
```
