### ISSUE TITLE
[enhancement] Allow metadata field value to be used in styles

### ISSUE THREAD

**Issue by josineto** [msprev/panzer#49]
It would be nice if one could use values from metadata fields in styles definition. For instance, in a document:

```markdown
---
metadata: work3.yaml
style: MyStyle
---
# My document
```

And in `styles.yaml`:

```yaml
MyStyle:
  all:
    commandline:
      metadata-file: "`$metadata$`" # I suggest $ as it's syntax from Pandoc templates
```

In this case, panzer would put in command line `--metadata-file=work3.yaml` (I know this case would also need #48 to completely work).

Is it possible? (In the past I've already faced other situations where this would elegantly solve problems, but unfortunately I can't remember whose situations were those...)
