### ISSUE TITLE
Path relative to files

### ISSUE THREAD

**Issue by jgrizou** [msprev/panzer#5]
I have been trying panzer a lot today. It is very convenient, good work!

To me, it would be useful to be able to define path realtive to files and not to the directory panzer is executed, e.g.

```

---
style: Default
styledef:
  Default:
    all:
      commandline:
        standalone: true
        include-in-header:
          - "` $pathtothisfile$/header_addon.html`"

---

Hello World!
```

Let's call this file website/sitesrc/project/projectOne.md (see below).

I have no idea about which syntax can be used and wether it is possible. Yet, it seems convenient when automatizing panzer calls. For example, if one wants to build a website, he will have to call panzer for all *.md files in a folder hierarchy and output in another folder under the same hierarchy, e.g.

Currently (with `include-in-header: "`header_addon.html`"`) we must do:

```
cd website/sitesrc/project/projectOne.md
panzer projectOne.md -o ../../../sitebin/project/projectOne.html
```

Seems nicer if it could work like that:

```
panzer website/sitesrc/project/projectOne.md -o website/sitebin/project/projectOne.html
```

(with relative path for  `include-in-header: "`$pathtothisfile$/header_addon.html`"`)

If you think of building a serie of scripts that automate calls to panzer, the second option is easier to manage. And having the option to use relative paths is always nice :)
