### ISSUE TITLE
Repeated 'header-includes'

### ISSUE THREAD

**Issue by twsh** [msprev/panzer#6]
When there there several uses of 'header-includes' in the style file only the last one is used. If I've understood the code right, the issue is that 'header-includes' isn't one of the additive options.

**Comment by msprev** [comment]
`$header-includes$` is the name of the template variable in pandoc that gets populated by pandoc's command line option `-H/--include-in-header`. 

What you want is to provide panzer with this in your metadata block or style definition:

```
commandline:
    include-in-header:
        - "`file1.txt`"
        - "`file2.txt`"
        - "`file3.txt`"
```

This will set pandoc's command line option appropriately (alternatively, this command line option can also be passed direct to panzer).

Let me know if this doesn't solve the probelm.

**Comment by twsh** [comment]
Thanks. I had been setting the metadata value directly from the command line with Pandoc for years. It works, but it's not correct.

Using the correct method I can have multiple included files defined in one style, but if I define a child style I don't get the includes inherited from the parent.

Here's an example 'style.yaml':

```
Base:
    latex:
        commandline:
            standalone: true

Foo:
    parent:
        - Base
    latex:
        commandline:
            include-in-header:
                - "`foo.tex`"

Bar:
    parent:
        - Foo
    latex:
        commandline:
            include-in-header:
                - "`bar.tex`"
```

When I tested it a document with style Bar has the content of bar.tex in its header, but not foo.tex. Is that the way Panzer is designed? It's not a big issue, because I can always add the parent's includes to the child too.
